// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: lab.proto

package lab

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmplitudeVpp  float32                `protobuf:"fixed32,1,opt,name=amplitude_vpp,json=amplitudeVpp,proto3" json:"amplitude_vpp,omitempty"`
	Waveform      string                 `protobuf:"bytes,2,opt,name=waveform,proto3" json:"waveform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_lab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{0}
}

func (x *SetupRequest) GetAmplitudeVpp() float32 {
	if x != nil {
		return x.AmplitudeVpp
	}
	return 0
}

func (x *SetupRequest) GetWaveform() string {
	if x != nil {
		return x.Waveform
	}
	return ""
}

type SetupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupResponse) Reset() {
	*x = SetupResponse{}
	mi := &file_lab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponse) ProtoMessage() {}

func (x *SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponse.ProtoReflect.Descriptor instead.
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{1}
}

func (x *SetupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetupResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GeneratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrequencyHz   float32                `protobuf:"fixed32,1,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	AmplitudeVpp  float32                `protobuf:"fixed32,2,opt,name=amplitude_vpp,json=amplitudeVpp,proto3" json:"amplitude_vpp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratorRequest) Reset() {
	*x = GeneratorRequest{}
	mi := &file_lab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorRequest) ProtoMessage() {}

func (x *GeneratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorRequest.ProtoReflect.Descriptor instead.
func (*GeneratorRequest) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratorRequest) GetFrequencyHz() float32 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *GeneratorRequest) GetAmplitudeVpp() float32 {
	if x != nil {
		return x.AmplitudeVpp
	}
	return 0
}

type GeneratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratorResponse) Reset() {
	*x = GeneratorResponse{}
	mi := &file_lab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorResponse) ProtoMessage() {}

func (x *GeneratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorResponse.ProtoReflect.Descriptor instead.
func (*GeneratorResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{3}
}

func (x *GeneratorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MeasureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrequencyHz   float32                `protobuf:"fixed32,1,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	Timebase      string                 `protobuf:"bytes,2,opt,name=timebase,proto3" json:"timebase,omitempty"`
	Vscale        string                 `protobuf:"bytes,3,opt,name=vscale,proto3" json:"vscale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureRequest) Reset() {
	*x = MeasureRequest{}
	mi := &file_lab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureRequest) ProtoMessage() {}

func (x *MeasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureRequest.ProtoReflect.Descriptor instead.
func (*MeasureRequest) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{4}
}

func (x *MeasureRequest) GetFrequencyHz() float32 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *MeasureRequest) GetTimebase() string {
	if x != nil {
		return x.Timebase
	}
	return ""
}

func (x *MeasureRequest) GetVscale() string {
	if x != nil {
		return x.Vscale
	}
	return ""
}

type MeasureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VinVpp        float32                `protobuf:"fixed32,1,opt,name=vin_vpp,json=vinVpp,proto3" json:"vin_vpp,omitempty"`
	VoutVpp       float32                `protobuf:"fixed32,2,opt,name=vout_vpp,json=voutVpp,proto3" json:"vout_vpp,omitempty"`
	PhaseShiftDeg float32                `protobuf:"fixed32,3,opt,name=phase_shift_deg,json=phaseShiftDeg,proto3" json:"phase_shift_deg,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureResponse) Reset() {
	*x = MeasureResponse{}
	mi := &file_lab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureResponse) ProtoMessage() {}

func (x *MeasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureResponse.ProtoReflect.Descriptor instead.
func (*MeasureResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{5}
}

func (x *MeasureResponse) GetVinVpp() float32 {
	if x != nil {
		return x.VinVpp
	}
	return 0
}

func (x *MeasureResponse) GetVoutVpp() float32 {
	if x != nil {
		return x.VoutVpp
	}
	return 0
}

func (x *MeasureResponse) GetPhaseShiftDeg() float32 {
	if x != nil {
		return x.PhaseShiftDeg
	}
	return 0
}

func (x *MeasureResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_lab_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{6}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_lab_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lab_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_lab_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_lab_proto protoreflect.FileDescriptor

const file_lab_proto_rawDesc = "" +
	"\n" +
	"\tlab.proto\x12\x03lab\"O\n" +
	"\fSetupRequest\x12#\n" +
	"\ramplitude_vpp\x18\x01 \x01(\x02R\famplitudeVpp\x12\x1a\n" +
	"\bwaveform\x18\x02 \x01(\tR\bwaveform\"F\n" +
	"\rSetupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"Z\n" +
	"\x10GeneratorRequest\x12!\n" +
	"\ffrequency_hz\x18\x01 \x01(\x02R\vfrequencyHz\x12#\n" +
	"\ramplitude_vpp\x18\x02 \x01(\x02R\famplitudeVpp\"-\n" +
	"\x11GeneratorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x0eMeasureRequest\x12!\n" +
	"\ffrequency_hz\x18\x01 \x01(\x02R\vfrequencyHz\x12\x1a\n" +
	"\btimebase\x18\x02 \x01(\tR\btimebase\x12\x16\n" +
	"\x06vscale\x18\x03 \x01(\tR\x06vscale\"\x8a\x01\n" +
	"\x0fMeasureResponse\x12\x17\n" +
	"\avin_vpp\x18\x01 \x01(\x02R\x06vinVpp\x12\x19\n" +
	"\bvout_vpp\x18\x02 \x01(\x02R\avoutVpp\x12&\n" +
	"\x0fphase_shift_deg\x18\x03 \x01(\x02R\rphaseShiftDeg\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"\x11\n" +
	"\x0fShutdownRequest\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x84\x02\n" +
	"\x14InstrumentController\x129\n" +
	"\x10SetupInstruments\x12\x11.lab.SetupRequest\x1a\x12.lab.SetupResponse\x12=\n" +
	"\fSetGenerator\x12\x15.lab.GeneratorRequest\x1a\x16.lab.GeneratorResponse\x129\n" +
	"\fMeasurePoint\x12\x13.lab.MeasureRequest\x1a\x14.lab.MeasureResponse\x127\n" +
	"\bShutdown\x12\x14.lab.ShutdownRequest\x1a\x15.lab.ShutdownResponseB/Z-github.com/JingolBong/schemotech/internal/labb\x06proto3"

var (
	file_lab_proto_rawDescOnce sync.Once
	file_lab_proto_rawDescData []byte
)

func file_lab_proto_rawDescGZIP() []byte {
	file_lab_proto_rawDescOnce.Do(func() {
		file_lab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)))
	})
	return file_lab_proto_rawDescData
}

var file_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lab_proto_goTypes = []any{
	(*SetupRequest)(nil),      // 0: lab.SetupRequest
	(*SetupResponse)(nil),     // 1: lab.SetupResponse
	(*GeneratorRequest)(nil),  // 2: lab.GeneratorRequest
	(*GeneratorResponse)(nil), // 3: lab.GeneratorResponse
	(*MeasureRequest)(nil),    // 4: lab.MeasureRequest
	(*MeasureResponse)(nil),   // 5: lab.MeasureResponse
	(*ShutdownRequest)(nil),   // 6: lab.ShutdownRequest
	(*ShutdownResponse)(nil),  // 7: lab.ShutdownResponse
}
var file_lab_proto_depIdxs = []int32{
	0, // 0: lab.InstrumentController.SetupInstruments:input_type -> lab.SetupRequest
	2, // 1: lab.InstrumentController.SetGenerator:input_type -> lab.GeneratorRequest
	4, // 2: lab.InstrumentController.MeasurePoint:input_type -> lab.MeasureRequest
	6, // 3: lab.InstrumentController.Shutdown:input_type -> lab.ShutdownRequest
	1, // 4: lab.InstrumentController.SetupInstruments:output_type -> lab.SetupResponse
	3, // 5: lab.InstrumentController.SetGenerator:output_type -> lab.GeneratorResponse
	5, // 6: lab.InstrumentController.MeasurePoint:output_type -> lab.MeasureResponse
	7, // 7: lab.InstrumentController.Shutdown:output_type -> lab.ShutdownResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lab_proto_init() }
func file_lab_proto_init() {
	if File_lab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lab_proto_rawDesc), len(file_lab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lab_proto_goTypes,
		DependencyIndexes: file_lab_proto_depIdxs,
		MessageInfos:      file_lab_proto_msgTypes,
	}.Build()
	File_lab_proto = out.File
	file_lab_proto_goTypes = nil
	file_lab_proto_depIdxs = nil
}
