// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: lab.proto

package lab

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstrumentController_SetupInstruments_FullMethodName = "/lab.InstrumentController/SetupInstruments"
	InstrumentController_SetGenerator_FullMethodName     = "/lab.InstrumentController/SetGenerator"
	InstrumentController_MeasurePoint_FullMethodName     = "/lab.InstrumentController/MeasurePoint"
	InstrumentController_Shutdown_FullMethodName         = "/lab.InstrumentController/Shutdown"
)

// InstrumentControllerClient is the client API for InstrumentController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstrumentControllerClient interface {
	SetupInstruments(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error)
	SetGenerator(ctx context.Context, in *GeneratorRequest, opts ...grpc.CallOption) (*GeneratorResponse, error)
	MeasurePoint(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*MeasureResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type instrumentControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewInstrumentControllerClient(cc grpc.ClientConnInterface) InstrumentControllerClient {
	return &instrumentControllerClient{cc}
}

func (c *instrumentControllerClient) SetupInstruments(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupResponse)
	err := c.cc.Invoke(ctx, InstrumentController_SetupInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentControllerClient) SetGenerator(ctx context.Context, in *GeneratorRequest, opts ...grpc.CallOption) (*GeneratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratorResponse)
	err := c.cc.Invoke(ctx, InstrumentController_SetGenerator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentControllerClient) MeasurePoint(ctx context.Context, in *MeasureRequest, opts ...grpc.CallOption) (*MeasureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeasureResponse)
	err := c.cc.Invoke(ctx, InstrumentController_MeasurePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentControllerClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, InstrumentController_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstrumentControllerServer is the server API for InstrumentController service.
// All implementations must embed UnimplementedInstrumentControllerServer
// for forward compatibility.
type InstrumentControllerServer interface {
	SetupInstruments(context.Context, *SetupRequest) (*SetupResponse, error)
	SetGenerator(context.Context, *GeneratorRequest) (*GeneratorResponse, error)
	MeasurePoint(context.Context, *MeasureRequest) (*MeasureResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedInstrumentControllerServer()
}

// UnimplementedInstrumentControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstrumentControllerServer struct{}

func (UnimplementedInstrumentControllerServer) SetupInstruments(context.Context, *SetupRequest) (*SetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupInstruments not implemented")
}
func (UnimplementedInstrumentControllerServer) SetGenerator(context.Context, *GeneratorRequest) (*GeneratorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGenerator not implemented")
}
func (UnimplementedInstrumentControllerServer) MeasurePoint(context.Context, *MeasureRequest) (*MeasureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MeasurePoint not implemented")
}
func (UnimplementedInstrumentControllerServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedInstrumentControllerServer) mustEmbedUnimplementedInstrumentControllerServer() {}
func (UnimplementedInstrumentControllerServer) testEmbeddedByValue()                              {}

// UnsafeInstrumentControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstrumentControllerServer will
// result in compilation errors.
type UnsafeInstrumentControllerServer interface {
	mustEmbedUnimplementedInstrumentControllerServer()
}

func RegisterInstrumentControllerServer(s grpc.ServiceRegistrar, srv InstrumentControllerServer) {
	// If the following call panics, it indicates UnimplementedInstrumentControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstrumentController_ServiceDesc, srv)
}

func _InstrumentController_SetupInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentControllerServer).SetupInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentController_SetupInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentControllerServer).SetupInstruments(ctx, req.(*SetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentController_SetGenerator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentControllerServer).SetGenerator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentController_SetGenerator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentControllerServer).SetGenerator(ctx, req.(*GeneratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentController_MeasurePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentControllerServer).MeasurePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentController_MeasurePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentControllerServer).MeasurePoint(ctx, req.(*MeasureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentController_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentControllerServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentController_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentControllerServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstrumentController_ServiceDesc is the grpc.ServiceDesc for InstrumentController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstrumentController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lab.InstrumentController",
	HandlerType: (*InstrumentControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupInstruments",
			Handler:    _InstrumentController_SetupInstruments_Handler,
		},
		{
			MethodName: "SetGenerator",
			Handler:    _InstrumentController_SetGenerator_Handler,
		},
		{
			MethodName: "MeasurePoint",
			Handler:    _InstrumentController_MeasurePoint_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _InstrumentController_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lab.proto",
}
