# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lab_pb2 as lab__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lab_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InstrumentControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetupInstruments = channel.unary_unary(
                '/lab.InstrumentController/SetupInstruments',
                request_serializer=lab__pb2.SetupRequest.SerializeToString,
                response_deserializer=lab__pb2.SetupResponse.FromString,
                _registered_method=True)
        self.SetGenerator = channel.unary_unary(
                '/lab.InstrumentController/SetGenerator',
                request_serializer=lab__pb2.GeneratorRequest.SerializeToString,
                response_deserializer=lab__pb2.GeneratorResponse.FromString,
                _registered_method=True)
        self.MeasurePoint = channel.unary_unary(
                '/lab.InstrumentController/MeasurePoint',
                request_serializer=lab__pb2.MeasureRequest.SerializeToString,
                response_deserializer=lab__pb2.MeasureResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/lab.InstrumentController/Shutdown',
                request_serializer=lab__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=lab__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class InstrumentControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetupInstruments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGenerator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MeasurePoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstrumentControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetupInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupInstruments,
                    request_deserializer=lab__pb2.SetupRequest.FromString,
                    response_serializer=lab__pb2.SetupResponse.SerializeToString,
            ),
            'SetGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGenerator,
                    request_deserializer=lab__pb2.GeneratorRequest.FromString,
                    response_serializer=lab__pb2.GeneratorResponse.SerializeToString,
            ),
            'MeasurePoint': grpc.unary_unary_rpc_method_handler(
                    servicer.MeasurePoint,
                    request_deserializer=lab__pb2.MeasureRequest.FromString,
                    response_serializer=lab__pb2.MeasureResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=lab__pb2.ShutdownRequest.FromString,
                    response_serializer=lab__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab.InstrumentController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lab.InstrumentController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InstrumentController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetupInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab.InstrumentController/SetupInstruments',
            lab__pb2.SetupRequest.SerializeToString,
            lab__pb2.SetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab.InstrumentController/SetGenerator',
            lab__pb2.GeneratorRequest.SerializeToString,
            lab__pb2.GeneratorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MeasurePoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab.InstrumentController/MeasurePoint',
            lab__pb2.MeasureRequest.SerializeToString,
            lab__pb2.MeasureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab.InstrumentController/Shutdown',
            lab__pb2.ShutdownRequest.SerializeToString,
            lab__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
